<template>
    <div class="intro-container">
        <div class="content-section">
            <h1 class="md-display-2">Hi</h1>
            <h2 class="md-display-2">I'm {{ name }}</h2>
            <p class="title">Full Stack Developer</p>
            <p class="description">Building elegant solutions to complex problems</p>
        </div>
        <div class="splash-container">
            <img src="../assets/splash1.webp" title="Generated by AI" class="splash-image">
        </div>
    </div>
</template>

<script setup lang="ts">
defineProps<{
    name: string;
}>();

</script>

<style scoped>
.intro-container {
    display: flex;
    align-items: center;
    padding: 0rem;
}

.content-section {
    flex: 0 1 40%;
    display: flex;
    flex-direction: column;
    justify-content: center;
}

.splash-container {
    flex: 0 1 60%;
    height: 100%;
    overflow: hidden;
}

.splash-image {
    width: 100%;
    height: 100%;
    object-fit: cover;
    border-radius: 10px;
}

@media (max-width: 768px) {
    .intro-container {
        flex-direction: column-reverse;
        padding: 1rem;
    }

    .content-section,
    .splash-container {
        flex: 1 1 100%;
    }
}

.md-display-2 {
    font-size: 3rem;
    font-weight: 300;
    letter-spacing: -0.5px;
    margin-bottom: 1rem;
    margin-top: 0;
    color: var(--md-on-surface);
}

.title {
    color: var(--md-primary);
    font-size: 1.5rem;
    margin: 1rem 0;
    font-weight: 500;
}

.description {
    color: var(--md-on-surface);
    font-size: 1.25rem;
    margin: 1rem 0;
    opacity: 0.87;
}
</style>